"""Callback base class — subset of the PL Callback hook surface.

Phase 1 commits to:
- ``setup``, ``teardown``
- ``on_train_start`` / ``on_train_end``
- ``on_train_epoch_start`` / ``on_train_epoch_end``
- ``on_validation_epoch_start`` / ``on_validation_epoch_end``
- ``on_train_batch_start`` / ``on_train_batch_end``
- ``on_validation_batch_start`` / ``on_validation_batch_end``

Other hooks will land alongside the features that need them (e.g.
``on_save_checkpoint`` arrives with ``ModelCheckpoint`` in Phase 3).
"""
from __future__ import annotations

from typing import Any


class Callback:
    """No-op default; subclasses override the hooks they care about."""

    def setup(self, trainer, pl_module, stage: str) -> None: ...
    def teardown(self, trainer, pl_module, stage: str) -> None: ...

    def on_train_start(self, trainer, pl_module) -> None: ...
    def on_train_end(self, trainer, pl_module) -> None: ...

    def on_train_epoch_start(self, trainer, pl_module) -> None: ...
    def on_train_epoch_end(self, trainer, pl_module) -> None: ...

    def on_validation_epoch_start(self, trainer, pl_module) -> None: ...
    def on_validation_epoch_end(self, trainer, pl_module) -> None: ...

    def on_train_batch_start(self, trainer, pl_module, batch: Any, batch_idx: int) -> None: ...
    def on_train_batch_end(self, trainer, pl_module, outputs: Any, batch: Any, batch_idx: int) -> None: ...

    def on_validation_batch_start(self, trainer, pl_module, batch: Any, batch_idx: int) -> None: ...
    def on_validation_batch_end(self, trainer, pl_module, outputs: Any, batch: Any, batch_idx: int) -> None: ...
